- name: Query hostname to host IPv4 address
  set_fact:
    role_bi_hostname_tmp_dns_ptr_name_ipv4: '{{ lookup("community.general.dig", ansible_default_ipv4["address"] + "/PTR") | regex_replace("\.$", "") if "address" in ansible_default_ipv4 | default(false) else ""}}'

- name: Query hostname to host IPv6 address
  set_fact:
    role_bi_hostname_tmp_dns_ptr_name_ipv6: '{{ lookup("community.general.dig", ansible_default_ipv6["address"] + "/PTR") | regex_replace("\.$", "") if "address" in ansible_default_ipv6 | default(false) else ""}}'

- name: Generate error when ipv4 and ipv6 hostnames differ
  fail:
    msg: The ipv4 and ipv6 reverse names to this hosts IP differ.
  when:
    - role_bi_hostname_tmp_dns_ptr_name_ipv4 != ""
    - role_bi_hostname_tmp_dns_ptr_name_ipv6 != ""
    - role_bi_hostname_tmp_dns_ptr_name_ipv4 != role_bi_hostname_tmp_dns_ptr_name_ipv6

- name: Generate error when there is not reverse DNS hostname for ipv4 and ipv6
  fail:
    msg: There can no reverse DNS hostname be found for this hosts IP
  when:
    - role_bi_hostname_tmp_dns_ptr_name_ipv4 == ""
    - role_bi_hostname_tmp_dns_ptr_name_ipv6 == ""

- name: Select definite fqdn
  set_fact:
    role_bi_hostname_tmp_fqdn: '{{ role_bi_hostname_tmp_dns_ptr_name_ipv4 if role_bi_hostname_tmp_dns_ptr_name_ipv4 != "" else role_bi_hostname_tmp_dns_ptr_name_ipv6 }}'

- name: Set short hostname
  set_fact:
    role_bi_hostname_tmp_short_hostname: '{{ role_bi_hostname_tmp_fqdn.split(".")[0] }}'

- name: Set short inventory_hostname
  set_fact:
    role_bi_hostname_tmp_short_inventory_hostname: '{{ inventory_hostname.split(".")[0] }}'

- name: Generate warning, when there are differences between inventory_hostname, ansible_hostname and DNS PTR
  fail:
    msg: 'Inconsistent naming: hostname portion inventory_hostname = "{{role_bi_hostname_tmp_short_inventory_hostname}}" role_bi_hostname_tmp_short_hostname = "{{ role_bi_hostname_tmp_short_hostname }}"'
  when:
    - role_bi_hostname_tmp_short_inventory_hostname != role_bi_hostname_tmp_short_hostname

- name: debug
  debug:
    var: role_bi_hostname_tmp_dns_ptr_name_ipv4

- name: Set hostname on host
  hostname:
    name: '{{ role_bi_hostname_tmp_short_hostname }}'

- name: "Create /etc/hosts"
  template:
    src: templates/etc_hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
