- name: Set hostname according to inventory_hostname CentOS.
  shell: nmcli general hostname {{ inventory_hostname }}; hostname {{ inventory_hostname }}
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or
        (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8")

- block:
    - name: Configure hostname according to inventory-hostname for Debian system.
      template:
        src: templates/etc_hostname.j2
        dest: /etc/hostname
        owner: root
        group: root
        mode: '0644'
    - name: Set hostname according to inventory_hostname Debian.
      shell: nmcli general hostname {{ inventory_hostname }}; hostname {{ inventory_hostname }}
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "8") or
        (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "10") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "14.04")

- name: "Create /etc/hosts"
  template:
    src: templates/etc_hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
